name: First action

on:
  workflow_dispatch:

jobs:
  print-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print branch name
        run: |
          echo "Branch: ${GITHUB_REF##*/}"
  
  test-branch:
    uses: ./.github/workflows/reusable-action.yml
