name: ecr

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      aws-role:
        required: true
        type: string
      dockerfile-path:
        required: false
        type: string
        description: 'Optional: Relative path to the Dockerfile and its context, e.g., ./services/service1'

jobs:
  build-push-to-ecr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Determine build context
        id: context
        run: |
          if [ -z "${{ inputs.dockerfile-path }}" ]; then
            echo "build_context=all" >> "$GITHUB_OUTPUT"
          else
            echo "build_context=single" >> "$GITHUB_OUTPUT"
            echo "dir_name=$(basename ${{ inputs.dockerfile-path }})" >> "$GITHUB_OUTPUT"
          fi

      - name: Build and push Docker image (single context)
        if: steps.context.outputs.build_context == 'single'
        env:
          REPO_NAME: app-repo
          DIR_NAME: ${{ steps.context.outputs.dir_name }}
        run: |
          echo "/${REPO_NAME}/${DIR_NAME}:${GITHUB_REF#refs/*/}"

      - name: Build all services
        if: steps.context.outputs.build_context == 'all'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPO_NAME: app-repo
        run: |
          echo "all services"
