name: Reusable action

on:
  workflow_call:
  
jobs:
  print-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print branch name
        run: |
          echo "Branch: ${{ github.ref }}"
