name: Test Pull Request

on:
  pull_request:
    branches: ["main"]
    paths-ignore:
      - '.github/workflows/**'
      - 'services/**/deployment/**'

jobs:
  test-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Test changes
        run: echo "there are changes in the pr"