name: Test ENV Condition

on:
  workflow_dispatch:
    inputs:
      is_release_version:
        description: "'true' if we need to create a new ReadMe version"
        required: true
        type: string
env:
  IS_RELEASE_VERSION: ${{ inputs.is_release_version || 'false' }}
  TMP_DIR: './tmp'
  OPENAPI_FILE: 'openapi.json'
  
jobs:
  setup-and-create-version:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        if: ${{ env.IS_RELEASE_VERSION == 'true' }}
        run: echo "ok"

      - name: Create dir and file
        run: |
          mkdir ${{ env.TMP_DIR }}
          echo "bla" > ${{ env.TMP_DIR }}/${{ env.OPENAPI_FILE }}
          cat ${{ env.TMP_DIR }}/${{ env.OPENAPI_FILE }}

          echo "Test print env direct"
          echo "dir is: ${TMP_DIR}"
          echo "file is: ${OPENAPI_FILE}"
